### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by oupala** [TailorBrands/docker-libvips#4]
I don't understand how to use this image.

Can I use npx inside the image?

Something like: `npx sharp-cli <parameters>`?

I installed `sharp` and `sharp-cli`, but I'm not able to use it after installing...

I want to use sharp and sharp-cli as an npm module called with  ̀npx`.

This is what I am doing:

```bash
docker run -it --rm tailor/docker-libvips:node-10.9 /bin/bash
npx sharp-cli
```

and the error is:

> internal/modules/cjs/loader.js:583
    throw err;
    ^
> 
> Error: Cannot find module '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/.node-gyp/10.9.0'
gyp ERR! System Linux 4.9.0-9-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-14T00_09_09_733Z-debug.log
Install for sharp-cli@latest failed with code 1

`npx` seems to install sharp-cli, but then does not find it (`Cannot find module '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'`). That's strange...

**Comment by oupala** [comment]
It seems the problem comes from running the container as root. See the other issue mentionned by @lovell to find out more.
